#!/usr/bin/env bash

set -euo pipefail

echo "Homebrew setup"
brew bundle --file ~/.dotfiles/setup/Brewfile

echo "Linking dotfiles"
ln -sf ~/.dotfiles/general/.skhdrc ~/.skhdrc
skhd --restart-service
